### ISSUE TITLE
微信里面的淘宝链接跳转，无法直接跳转。

### ISSUE THREAD

**Issue by lantex** [OldPanda/Open-the-F-king-URL-Right-Now#1]
直接po地址似乎会暴露隐私。
ps，我本想转成短链接发，结果发现 http://t.cn/ 的也没有直接跳转。不知道是否是我这里的问题。
version 0.5.1

**Comment by OldPanda** [comment]
这是个已知的问题，并且[少数派的文章](https://sspai.com/post/63252)也提到过，不过我至今还没有找到一篇带淘宝链接的微信公众号文章，无法测试，不介意的话希望能在这里贴一下

**Comment by lantex** [comment]
> 这是个已知的问题，并且[少数派的文章](https://sspai.com/post/63252)也提到过，不过我至今还没有找到一篇带淘宝链接的微信公众号文章，无法测试，不介意的话希望能在这里贴一下

我不是在少数派看到的，不知道您提过。你可以在聊天界面直接发 www.taobao.com 再点击网址就可以了，不必使用公众号。

**Comment by OldPanda** [comment]
在[最新版](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/commit/442c819d9d572dbd569bd5e1a1c54d44924cf386)中已经修复了这个问题，并同步到 [Greasy Fork](https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now) 上了
