### ISSUE TITLE
脚本能用，但还有一些问题

### ISSUE THREAD

**Issue by OldPanda** [OldPanda/Open-the-F-king-URL-Right-Now#101]
跳转微信链接是有问题的，比如这个链接：https://link.zhihu.com/?target=https%3A%2F%2Fmp.weixin.qq.com%2Fs%2FTSpWaYSUpjeR_wzSclCTQA，希望能修复一下

issue 来源： https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now/discussions/195405

**Comment by imhansai** [comment]
看了一下，也是 URL 编码的问题，请看一下 #102 :)
