### ISSUE TITLE
打开mozilla.com时跳转中国特供版url firefox.com.cn

### ISSUE THREAD

**Issue by charle00001** [OldPanda/Open-the-F-king-URL-Right-Now#103]
如题，能不能加一个不让他跳转的链接

**Comment by OldPanda** [comment]
@charle00001 禁止跳转的功能加在这个插件里似乎不妥，你可以试试[在浏览器层面禁止访问 `firefox.com.cn`](www.hostinger.com/tutorials/how-to-block-a-website)

**Comment by OldPanda** [comment]
长时间不活跃，关了
