### ISSUE TITLE
实测还是会短暂跳到一个“确认跳转”的页面

### ISSUE THREAD

**Issue by litanyue** [OldPanda/Open-the-F-king-URL-Right-Now#11]
现象：
          在知乎点击外站链接还是会短暂的跳到一个“是否要跳转”的页面
建议：
          能否在 js 里直接把 url 修改掉，而不是跳转时再跳到另一个url

**Comment by AlanMaxxx** [comment]
> 现象：
> 在知乎点击外站链接还是会短暂的跳到一个“是否要跳转”的页面
> 建议：
> 能否在 js 里直接把 url 修改掉，而不是跳转时再跳到另一个url

是的，我也遇到了这个问题！

**Comment by OldPanda** [comment]
不好意思，目前暂时没有这个计划，对于用户体验尚可的页面，还是尽量不想去改动它的源码
