### ISSUE TITLE
请求添加腾讯云开发者社区

### ISSUE THREAD

**Issue by SuiYunsy** [OldPanda/Open-the-F-king-URL-Right-Now#113]
腾讯云开发者社区文章 https://cloud.tencent.com/developer/article/2232806 里的两个链接
![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/104718844/c21953f5-4a6a-4833-829a-1f14990b8149)
- https://cloud.tencent.com/developer/tools/blog-entry?target=https%3A%2F%2Fbetteruptime.com%2F&source=article&objectId=2232806
- https://cloud.tencent.com/developer/tools/blog-entry?target=https%3A%2F%2Fgithub.com%2Feidam%2Fcf-workers-status-page&source=article&objectId=2232806

希望作者大大可以拨冗适配~~
您的脚本非常好用，顺祝您龙年大吉！😊

**Comment by OldPanda** [comment]
新年快乐！谢谢您的支持与反馈！腾讯云开发者社区将于下个版本支持，祝使用愉快！
