### ISSUE TITLE
公众号已迁移

### ISSUE THREAD

**Issue by zheng7fu2** [OldPanda/Open-the-F-king-URL-Right-Now#117]
像这种 
https://mp.weixin.qq.com/s?__biz=MzU2Mjg0NjkxMw==&mid=2247486299&idx=1&sn=d0376168c261b5b7b15b50e5cd53cf6d&chksm=fc6206f5cb158fe3e673ab329c94b138566363931161946112a434fc35d58add886f1dd360b2&scene=21#wechat_redirect

公众号已迁移，可以直接跳转打开文章吗？

**Comment by OldPanda** [comment]
万万没想到还有这种情况，我抽时间支持一下吧。谢谢反馈！
