### ISSUE TITLE
申请2个『超不链接』的网站链接跳转直达，谢谢！

### ISSUE THREAD

**Issue by sleepinghua** [OldPanda/Open-the-F-king-URL-Right-Now#17]
以下2个网站经常使用，网站里的链接一直无法直达，需要二次点击跳转，如下为跳转链接页面：

1. 腾讯文档（docs.qq.com）
![Snipaste_2021-02-01_20-53-50](https://user-images.githubusercontent.com/4011353/106463247-24e79a80-64d2-11eb-9771-b1949ad86f66.png)

2. pixiv.net
![Snipaste_2021-02-01_21-04-16](https://user-images.githubusercontent.com/4011353/106463563-90316c80-64d2-11eb-9921-bbe688272399.png)

希望所有超链接都能链接~谢谢！

**Comment by cztchoice** [comment]
请直接给出链接地址，截图没法使用

**Comment by sleepinghua** [comment]
> 请直接给出链接地址，截图没法使用

[https://docs.qq.com/scenario/link.html?url=https%3A%2F%2Fpan.baidu.com%2Fs%2F1-AzaZ0HtVD_0NjYbkfkP1w&pid=300000000$bsjGhbFmjZwC&cid=144115210302878961](https://docs.qq.com/scenario/link.html?url=https%3A%2F%2Fpan.baidu.com%2Fs%2F1-AzaZ0HtVD_0NjYbkfkP1w&pid=300000000$bsjGhbFmjZwC&cid=144115210302878961)


[https://www.pixiv.net/jump.php?url=https%3A%2F%2Ftwitter.com%2Fy_o_m_y_o_m](https://www.pixiv.net/jump.php?url=https%3A%2F%2Ftwitter.com%2Fy_o_m_y_o_m)

**Comment by cztchoice** [comment]
https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/pull/16/files

你照着这个提一个PR？

**Comment by sleepinghua** [comment]
> https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/pull/16/files
> 
> 你照着这个提一个PR？

👌
