### ISSUE TITLE
繁体使用时的问题

### ISSUE THREAD

**Issue by lantex** [OldPanda/Open-the-F-king-URL-Right-Now#2]
很高兴看到您的快速更新，但我打开后仍无法跳转，之前我提到我的t.cn也是一样的问题。
查看了一下源代码，发现我的页面提示是繁体：”如果需要瀏覽，請長按網址複製後，使用瀏覽器查看。“，建议进一步修改，或更改逻辑。
谢谢

**Comment by OldPanda** [comment]
不好意思，没有考虑到繁体的情况

**Comment by OldPanda** [comment]
刚刚又更新了一个版本，得麻烦你验证一下管不管用

**Comment by lantex** [comment]
> 刚刚又更新了一个版本，得麻烦你验证一下管不管用

work
