### ISSUE TITLE
请求添加NGA论坛链接跳转支持

### ISSUE THREAD

**Issue by ssrkaze** [OldPanda/Open-the-F-king-URL-Right-Now#21]
请求添加NGA支持
NGA论坛有两种域名，以下是样例，1楼的第一行就是链接跳转，指向 http://kamitsubaki.jp/ 。
1. nga.178.com
   [[专楼]“KAMITSUBAKI STUDIO / 神椿”综合讨论贴](https://nga.178.com/read.php?tid=18934424)
2. bbs.nga.cn
   [[专楼]“KAMITSUBAKI STUDIO / 神椿”综合讨论贴](https://bbs.nga.cn/read.php?tid=18934424)

**Comment by OldPanda** [comment]
刚刚更新了最新版本，支持这两个网站
