### ISSUE TITLE
申请一个修改代码无法正常跳转的网站

### ISSUE THREAD

**Issue by sleepinghua** [OldPanda/Open-the-F-king-URL-Right-Now#27]
栗子：https://support.qq.com/products/57688/link-jump?jump=http://wukongshipin.com/?iao.su
该跳转链接属于[不死鸟分享](https://iao.su) [iao.su](https://iao.su)，点击网站分享的链接会跳转到以下形式的跳转链接（为什么用的是QQ的网站？）：

> https://support.qq.com/products/57688/link-jump?jump=

跳转截图：
![BaiduShurufa_2021-3-17_0-38-29](https://user-images.githubusercontent.com/4011353/111347157-e2f96900-86b9-11eb-8795-6845e9fb2a1f.png)

修改代码，会跳转到：

>https://support.qq.com/products/57688/null

跳转失败截图：
![BaiduShurufa_2021-3-17_0-38-45](https://user-images.githubusercontent.com/4011353/111347403-2358e700-86ba-11eb-8af1-8455344d1de3.png)

代码看不懂，怎么改，求大佬指教~

**Comment by OldPanda** [comment]
我发现这个网站并不会故意妨碍外链的跳转，比如说 https://iao.su/1492/ 里的链接，我试了几个都能直接打开，可能那个 QQ 的外链是原贴楼主自己发上去的？

**Comment by sleepinghua** [comment]
> 我发现这个网站并不会故意妨碍外链的跳转，比如说 https://iao.su/1492/ 里的链接，我试了几个都能直接打开，可能那个 QQ 的外链是原贴楼主自己发上去的？

嗯，是的，有的页面的链接加了跳转，有的没有~不明所以。Nevermind~
