### ISSUE TITLE
微信引用部分链接没有高亮

### ISSUE THREAD

**Issue by pixiandouban** [OldPanda/Open-the-F-king-URL-Right-Now#29]
文章地址：https://mp.weixin.qq.com/s/6MrwYxW1GBzvp0ok3EpSmQ

**Comment by OldPanda** [comment]
刚刚修复了这个问题 https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/commit/f2fb0e67fff974039324a6942cd3f9aaa4f7a283
