### ISSUE TITLE
知乎跳转时反复横跳，不能正常前往页面

### ISSUE THREAD

**Issue by Katemic** [OldPanda/Open-the-F-king-URL-Right-Now#3]

**Comment by OldPanda** [comment]
谢谢提 issue 反馈这个问题，能否捎带给个知乎链接？我好验证修复是否成功

**Comment by OldPanda** [comment]
我在自己的[知乎回答](https://www.zhihu.com/question/405829688/answer/1512234158)上试了一下，没有出现反复横跳的症状

**Comment by OldPanda** [comment]
今天在[这个链接](https://www.zhihu.com/pin/1306777283131068416)成功复现了一下，好像在尝试跳转正常外链时会出现这种状况，我会尽快修复

**Comment by OldPanda** [comment]
发布了一个新版本，现在上述两个知乎链接中的外链都无法复现『反复横跳』的症状了
