### ISSUE TITLE
微博文章推转 Github

### ISSUE THREAD

**Issue by pixiandouban** [OldPanda/Open-the-F-king-URL-Right-Now#30]
原文 https://weibo.com/ttarticle/p/show?id=2309404085964631887954
跳转链接 https://weibo.cn/sinaurl?u=https%3A%2F%2Fgithub.com%2FMrQianJinSi

网页提示：网页存在安全风险，为维护绿色上网环境， 已停止访问 

暂时用 https://addons.mozilla.org/en-US/firefox/addon/redirector/ 做了链接跳转

**Comment by OldPanda** [comment]
似乎跳转没有问题
![](https://media.giphy.com/media/tpqOZbgmky8uK3OBIg/giphy.gif)
