### ISSUE TITLE
(暴力猴)微信公众号图片和视频无法加载

### ISSUE THREAD

**Issue by vtnP5fR7SxAaMyU** [OldPanda/Open-the-F-king-URL-Right-Now#32]
暴力猴版本v2.12.12
控制变量测试过,而在油猴中正常
随便贴一个微信公众号的链接https://mp.weixin.qq.com/s/zke_fY8F-SCD7168-V7Xfg

**Comment by OldPanda** [comment]
谢谢提 issue ，刚刚在最新版本中修复了这个问题，欢迎更新试用
