### ISSUE TITLE
下载了，能用vscode打开，但是还是会出现跳转是为什么呀？

### ISSUE THREAD

**Issue by hermione999** [OldPanda/Open-the-F-king-URL-Right-Now#33]
求大佬解答，谢谢

**Comment by OldPanda** [comment]
这个脚本需要装在油猴插件上才能生效，
1. 去[这个网站](https://www.tampermonkey.net/)找到兼容你的浏览器的版本并安装
2. 然后去[这个链接](https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now)安装脚本，然后就可以了

祝使用愉快！

**Comment by hermione999** [comment]
谢谢大佬！！
但是安装之后还是会短暂的出现跳转页面，不过会自动跳转，这个之后会有修复吗？


| |
HermioneChen
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年5月19日 ***@***.***> 写道：

这个脚本需要装在油猴插件上才能生效，

去这个网站找到兼容你的浏览器的版本并安装
然后去这个链接安装脚本，然后就可以了

祝使用愉快！

**Comment by OldPanda** [comment]
跳转页面暂时没有去掉的打算，想的是尽量不去更改原有的页面内容
