### ISSUE TITLE
希望适配百度贴吧

### ISSUE THREAD

**Issue by vtnP5fR7SxAaMyU** [OldPanda/Open-the-F-king-URL-Right-Now#38]
可能因为贴吧放链接容易被吞，贴吧的跳转链接不太好找
https://tieba.baidu.com/p/7400319178
二楼里有个广告的链接

**Comment by Young-Lord** [comment]
地址：<http://jump.bdimg.com/safecheck/index?url=rN3wPs8te/rylt5DVsrRCg2Ji1OuLbWsb4bMpx7Pws85xPoz/6xAUn3NLCAQmrD1BD3KpeIruniJL5L0OKXImUQDLntvuP2/olBWPlcsUY8B64Jw7DXyrVNu45T3qGWCALDyuCPPsfcr6Kxs5D+bpO591nsNX2BG//Vs01T3xzmFottOJ+78haujwQMBgmRKVTdTKnzu/pgUpm7L79HjedOTYzqRoDeT1rPf4rnSWLDslN0/yNjeJqSwW+OuOScFeVlaskxghmFMSStzAXf1Ix8NwZv1SZPTUENdhaamh0xgYp5MPToF3VlYaN/1OCpk3vYXWEK/x6hZ3auM5nxVwNKZ4z64d3MUcGXAyGQPeNNuw6TyTjHtHe52bGsihhIPcovexuAqncYRSwzYocN9NDy+xFrRpK6eGXeMaIcYytKgwvfXEk+r6XY9qHh6BM0y>
