### ISSUE TITLE
微博国际版 App 分享的链接中，有 t.cn 短链接显示为文本格式

### ISSUE THREAD

**Issue by pixiandouban** [OldPanda/Open-the-F-king-URL-Right-Now#4]
举例如下链接：
http://weibointl.api.weibo.com/share/180619605.html
![微博链接](https://user-images.githubusercontent.com/50656651/97443957-94e00500-1966-11eb-8ad2-7454e06908d2.PNG)

**Comment by OldPanda** [comment]
目前只有微信公众号上的文本格式链接会被转换成可点击的链接，其他平台暂不支持

**Comment by pixiandouban** [comment]
找到了 一个脚本，支持上面的微博国际版，另外测了一个 哔哩哔哩的 专栏 和 视频介绍页也支持。可以作为参考补充。

脚本 Greasyfork 地址[Text-to-link](https://greasyfork.org/en/scripts/342-text-to-link)

**Comment by OldPanda** [comment]
额，发现链接只能返回空内容了
