### ISSUE TITLE
一篇微信公众号文章里的文本链接没有高亮显式

### ISSUE THREAD

**Issue by pixiandouban** [OldPanda/Open-the-F-king-URL-Right-Now#5]
文章如下
https://mp.weixin.qq.com/s/dDYt-iZQNIIdBWzxxRx_Iw
https://mp.weixin.qq.com/s/6yDyZy_9wQehJ6-wAxg5LQ

**Comment by OldPanda** [comment]
谢谢反馈，刚刚发布了一个新版本，现在两篇文章的显示效果分别如图所示
![image](https://user-images.githubusercontent.com/2587202/97955214-89bc1900-1d5a-11eb-9687-ae6f974c3bda.png)
![image](https://user-images.githubusercontent.com/2587202/97955233-92145400-1d5a-11eb-8d2b-aa29563eec83.png)
