### ISSUE TITLE
#科学上网时脚本doesn't work

### ISSUE THREAD

**Issue by CarfBook** [OldPanda/Open-the-F-king-URL-Right-Now#53]
运行环境： macOS  Firefox
登陆网站：知乎
梯子： clash
目前还不知道是什么原因。但是在点击知乎链接以后脚本并没有如愿执行。

**Comment by Young-Lord** [comment]
不能执行的链接是？关闭后是否可以正常执行？

**Comment by OldPanda** [comment]
此 issue 长期没动静，暂时关闭。

@CarfBook 如果问题还存在，欢迎重开或者提新的 issue ，谢谢！
