### ISSUE TITLE
微信文章无法显示图片

### ISSUE THREAD

**Issue by DazzlingGalaxy** [OldPanda/Open-the-F-king-URL-Right-Now#57]
例如
https://mp.weixin.qq.com/s/bw0x2jdhUreSAK5wu3Gy-w
https://mp.weixin.qq.com/s/2jEAYoKaENykGMwmWbSMJQ
https://mp.weixin.qq.com/s/hsLCs2INhN_wfhqflZgP0Q
脚本版本0.16.2，关闭脚本，以上网页中的图片能正常显示；开启脚本，图片一直在加载。
这个问题困扰我一段时间了，我在别的浏览器上就没问题，可每次都得切换到别的浏览器，太麻烦了。刚才详细对比后发现别的浏览器上我没用这个脚本，然后我关闭全部脚本，图片正常显示；只开这个脚本，图片一直在加载。

另外，我看到有用户反馈了同样的问题，其中第二个还是以前的，当时作者还回复已修复，怎么现在又出现了
https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now/discussions/125138
https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now/discussions/84038

**Comment by OldPanda** [comment]
在最近的 0.17.1 版本中再次修复了这个问题，上述三篇文章中的图片已可以正常显示，谢谢反馈！
