### ISSUE TITLE
百度百科 跳转

### ISSUE THREAD

**Issue by pixiandouban** [OldPanda/Open-the-F-king-URL-Right-Now#6]
不知道是否可以支持百度百科？

举例：
https://baike.baidu.com/redirect/6af44yMxpfopjVBNpn1SAv0giWqBhemJXVEI7X7gINYIKiqn4bv0SvOhw1JlbYb83aw_CthFUidVRFDOuUnK0rUFdXQ
[豆瓣网-百度百科](https://baike.baidu.com/item/%E8%B1%86%E7%93%A3%E7%BD%91)

**Comment by OldPanda** [comment]
谢谢建议，我去百度百科上看了下参考资料的外链，发现第一次跳转的地址呈现的实际上是该网页在某个时间点上的历史快照，比如说
![image](https://user-images.githubusercontent.com/2587202/100527857-7189bf00-318b-11eb-9c1d-9d80ea576fa2.png)
同一个 URL 上的内容确实有可能发生改变，所以作为百科类的网站，通过这种方式力求引用准确性是没有问题的，我不觉得这种情况是百度在恶意阻止用户访问原链接。
