### ISSUE TITLE
百度贴吧无法自动重定向

### ISSUE THREAD

**Issue by mobzila** [OldPanda/Open-the-F-king-URL-Right-Now#61]
比如说这个链接
http://[jump2.bdimg.com/safecheck/index?url=rN3wPs8te/pjz8pBqGzzzz3wi8AXlR5g1NgdDpM6gxIAXd05dt3m/x7iiUNBMf1rkVvOVeukx+fZa0Sr789sq5GvedOpCizeTDeOnqzMKitN/uxEXeos4Y5iD94p2hXY2AgCtjpDKkO+gYGq1Czi81SWSJ8XLuLbfSBwGF9mAgJ2Pah4egTNMg==](http://jump2.bdimg.com/safecheck/index?url=rN3wPs8te/pjz8pBqGzzzz3wi8AXlR5g1NgdDpM6gxIAXd05dt3m/x7iiUNBMf1rkVvOVeukx+fZa0Sr789sq5GvedOpCizeTDeOnqzMKitN/uxEXeos4Y5iD94p2hXY2AgCtjpDKkO+gYGq1Czi81SWSJ8XLuLbfSBwGF9mAgJ2Pah4egTNMg==)

**Comment by OldPanda** [comment]
https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/pull/42 已经在这里添加
