### ISSUE TITLE
微信文章中的视频无法显示和播放

### ISSUE THREAD

**Issue by DazzlingGalaxy** [OldPanda/Open-the-F-king-URL-Right-Now#64]
例如https://mp.weixin.qq.com/s/U89faZ6z50pu2Jk1skajKg
文章末尾"运行结果"中有视频，但开启脚本时，不显示视频，所以也不能播放，但IDM能探测到视频。关闭脚本时，视频能正常播放。脚本版本0.17.1。

**Comment by DazzlingGalaxy** [comment]
补充一个链接，https://mp.weixin.qq.com/s/bHlJjraIecm2Qrny0faLbA，视频界面能显示出来，但点击播放时无法播放。

**Comment by OldPanda** [comment]
这个貌似是链接替换时出了毛病，我抽空修一下，谢谢报告问题

**Comment by OldPanda** [comment]
应该已经修复了，祝使用愉快！
