### ISSUE TITLE
微博存在跳转不了的链接？！

### ISSUE THREAD

**Issue by sleepinghua** [OldPanda/Open-the-F-king-URL-Right-Now#67]
![image](https://user-images.githubusercontent.com/4011353/177044837-571dbf3e-385b-4f87-b71a-a0ec73b5ac7e.png)

https://weibo.cn/sinaurl?u=https%3A%2F%2Fwww.aliyundrive.com%2Fs%2FjCFAihaPtgV

网页提示也不同：**“网页存在安全风险，为维护绿色上网环境， 已停止访问”**

![image](https://user-images.githubusercontent.com/4011353/177044916-de2b3246-3484-4ef1-953e-3a1028a15512.png)
 但是脚本好像没有问题……@@
// https://weibo.cn/sinaurl?u=https%3A%2F%2Fwww.freebsd.org%2F  **可以跳转**

**Comment by OldPanda** [comment]
这个脚本对于微博的跳转逻辑是从网页的内容中读取需要跳转的链接，而非地址栏，所以那个“网页存在安全风险”的就跳不了了

**Comment by Lehmaning** [comment]
> 这个脚本对于微博的跳转逻辑是从网页的内容中读取需要跳转的链接，而非地址栏，所以那个“网页存在安全风险”的就跳不了了
解码URL并跳转实现应该不难吧？我试试看。另外直接读取URL跳转的话应该更安全更隐私，因为加载整个网页平台就有机会分析你对这个链接的行为。
