### ISSUE TITLE
建议加入csdn

### ISSUE THREAD

**Issue by nalanqingfeng** [OldPanda/Open-the-F-king-URL-Right-Now#7]

**Comment by OldPanda** [comment]
果不其然 CSDN 也开始干这种事了，找到一个示例链接 https://blog.csdn.net/codename_cys/article/details/111464123?depth_1-utm_source=distribute.pc_category.none-task-blog-hot-16.nonecase

**Comment by OldPanda** [comment]
刚刚添加了 csdn 的支持，用上面评论的链接试了下可行
