### ISSUE TITLE
希望添加企查查、天眼查

### ISSUE THREAD

**Issue by azsxdc0** [OldPanda/Open-the-F-king-URL-Right-Now#70]
不知道大佬有没有时间添加一下这两个网站，谢谢！！！

**Comment by OldPanda** [comment]
不好意思，天眼查不让境外访问，我看不到他们的跳转，企查查要求登录，还是等其他热心网友帮忙吧

**Comment by OldPanda** [comment]
@azsxdc0 刚刚注意到天眼查已经支持了 https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/pull/42
