### ISSUE TITLE
力扣跳转微信公众号文章出错

### ISSUE THREAD

**Issue by jameszzzqaq** [OldPanda/Open-the-F-king-URL-Right-Now#71]
链接如下：
https://leetcode.cn/link/?target=https://mp.weixin.qq.com/s?__biz=MzU4NDE3MTEyMA==&mid=2247489813&idx=1&sn=7f3bc18ca390d85b17655f7164d8e660

似乎是后半段的参数被丢掉了

**Comment by OldPanda** [comment]
刚刚修复了这个问题，如果还有其他的问题，欢迎反馈，祝使用愉快！
