### ISSUE TITLE
希望增加对简书（www.jianshu.com）的支持

### ISSUE THREAD

**Issue by Huanlan233** [OldPanda/Open-the-F-king-URL-Right-Now#75]
能不能增加该网站的支持，谢谢了！

**Comment by OldPanda** [comment]
@Huanlan233 已经支持简书了 https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/blob/master/userscript.js#L210 。如果不管用的话，能否麻烦你提供一个示例？

**Comment by Huanlan233** [comment]
抱歉，可能是由于电脑原因，刚安装上没起作用，在Greasyfork的搜索作用域时候输入成了"jiangshu"，我还以为没有将简书添加到彡(-_-;)彡
