### ISSUE TITLE
支持Instagram

### ISSUE THREAD

**Issue by XHXIAIEIN** [OldPanda/Open-the-F-king-URL-Right-Now#76]
```
// @match          https://www.instagram.com/linkshim/?u=*
```

```
    instagram: { match: 'https://www.instagram.com/linkshim/?u=', redirect: "url" },
```

![49](https://user-images.githubusercontent.com/45864744/208868845-e9eb7fed-cebc-459d-87e3-e6495a9831c0.png)

**Comment by OldPanda** [comment]
已搞定 https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/commit/6db30c643bf41b1c23e2473d960663562af57b3b
