### ISSUE TITLE
开启后微信公众号文章的图片无法加载

### ISSUE THREAD

**Issue by f59375543** [OldPanda/Open-the-F-king-URL-Right-Now#78]
比如说这个地址，关闭脚本后恢复正常

https://mp.weixin.qq.com/s/i8-Tp1GzLJvNj_SG5pcEIg

**Comment by OldPanda** [comment]
有可能跟[这个 issue](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/issues/64) 是同样的原因

**Comment by honestman9981** [comment]
直接在脚本设置 排除 mp.weixin.qq.com 刚刚测试没问题

**Comment by OldPanda** [comment]
应该已经修复了，祝使用愉快！

**Comment by f59375543** [comment]
> 应该已经修复了，祝使用愉快！

非常感谢

**Comment by XHXIAIEIN** [comment]
相同的原因，会导致微信公众号后台的图片显示异常，如登录二维码，公众号头像。

可能还需要排除这个域名
```
http://wx.qlogo.cn/*
```


![Snipaste_2023-01-06_15-47-09](https://user-images.githubusercontent.com/45864744/210956078-404822aa-e927-4be2-a86a-6db325a59a64.png)

![Snipaste_2023-01-06_15-47-56](https://user-images.githubusercontent.com/45864744/210956090-14c48788-6494-47ca-8dc1-80f202799f92.png)

![Snipaste_2023-01-06_15-45-3](https://user-images.githubusercontent.com/45864744/210956097-11615e72-07a3-4df9-a829-2520e20b612f.png)

**Comment by OldPanda** [comment]
@XHXIAIEIN 你好，方便给个 URL 吗？

**Comment by XHXIAIEIN** [comment]
> @XHXIAIEIN 你好，方便给个 URL 吗？

不好意思，忘记放链接了
https://mp.weixin.qq.com/

**Comment by XHXIAIEIN** [comment]
> 直接在脚本设置 排除 mp.weixin.qq.com 刚刚测试没问题

我排除 `https://mp.weixin.qq.com` 之后，就可以正常使用了。

**Comment by OldPanda** [comment]
@XHXIAIEIN 我没有微信公众号，不好验证，能不能麻烦你验证一下？谢谢！

**Comment by XHXIAIEIN** [comment]
测试了一下，虽然是解决了图片显示的问题，但控制台似乎还是会报错，可能是微信自己日常也会用到这个地址

![Snipaste_2023-01-07_11-25-53](https://user-images.githubusercontent.com/45864744/211129311-b00b6b69-af8a-4226-9ffc-677df722c2c5.png)

替换成这个地址就没问题了
```
https://mp.weixin.qq.com/s?src=*
```

**Comment by OldPanda** [comment]
谢谢帮忙！但新地址无法匹配公众号文章，比如说 https://mp.weixin.qq.com/s/vH-bD52kSauKQI0ScA7k_g

**Comment by OldPanda** [comment]
或者方便发一下公众号编辑控制台的 URL 吗？记得隐去隐私信息

**Comment by XHXIAIEIN** [comment]
编辑器后台是
```
https://mp.weixin.qq.com/cgi-bin/home?t=home/index&lang=zh_CN&token=*
```

**Comment by XHXIAIEIN** [comment]
我

> 谢谢帮忙！但新地址无法匹配公众号文章，比如说 https://mp.weixin.qq.com/s/vH-bD52kSauKQI0ScA7k_g

咦 我甚至没发现到公众号文章也有外链跳转，在哪里？

**Comment by OldPanda** [comment]
> 我甚至没发现到公众号文章也有外链跳转，在哪里？

这个 issue 最上面的那个[链接](https://mp.weixin.qq.com/s/i8-Tp1GzLJvNj_SG5pcEIg)里有很多外链。

能不能麻烦你试试在[第 49 行之前](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/blob/master/userscript.js#L49)插入
```
// @exclude        https://mp.weixin.qq.com/cgi-bin/home?*
```
然后试试看？

**Comment by XHXIAIEIN** [comment]
排除这个应该就没问题了
```
// @exclude        https://mp.weixin.qq.com/cgi-bin/*
```

**Comment by XHXIAIEIN** [comment]
抱歉 我没有看明白，公众号文章正文里面的 "链接" 本身就是纯文本，并不是超链接啊。匹配微信文章地址目的是想识别纯文本转换成超链接吗？

**Comment by OldPanda** [comment]
嗯，就是这个目的，可以把 `https://` 或者 `http://` 开头的地址转成超链接。谢谢验证！我去修一下
