### ISSUE TITLE
感谢开发优秀实用的脚本

### ISSUE THREAD

**Issue by autumoon** [OldPanda/Open-the-F-king-URL-Right-Now#8]
对于作者说的话，想必大家感同身受，类比当年的3Q大战，受伤的总是用户，感谢作者的辛苦付出，互联网越来越乌烟瘴气，劣币驱逐良币，无奈，希望能够回到正轨。

**Comment by OldPanda** [comment]
谢谢鼓励！希望这个脚本有一天再也没有用武之地
