### ISSUE TITLE
在打开微信链接的时候发现其中的图片显示一直加载

### ISSUE THREAD

**Issue by qinyixi** [OldPanda/Open-the-F-king-URL-Right-Now#9]
群友推荐，今天刚转上这个脚本，很明显地加快了跳转的速度，但是在使用中发现了一些问题，
在用网页打开微信中的链接时发现图片一直处于加载状态，不能显示，麻烦查一下原因

**Comment by OldPanda** [comment]
能否提供一个微信公众号的文章链接？

**Comment by OldPanda** [comment]
有网友在微博上和我详聊过这个问题，但我无法在本地复现，因此就无法定位问题根源，欢迎热心网友 PR
