### ISSUE TITLE
qq新版拦截页似乎无法跳转

### ISSUE THREAD

**Issue by WGzeyu** [OldPanda/Open-the-F-king-URL-Right-Now#95]
`https://c.pc.qq.com/middleb.html?pfurl=https%3A%2F%2Fgreasyfork.org%2Fzh-CN%2Fscripts%2F412612-open-the-f-king-url-right-now&pfuin=10000&pfto=&type=0&gjlevel=15&gjsublevel=2802`
https://c.pc.qq.com/middleb.html?pfurl=https%3A%2F%2Fgreasyfork.org%2Fzh-CN%2Fscripts%2F412612-open-the-f-king-url-right-now&pfuin=10000&pfto=&type=0&gjlevel=15&gjsublevel=2802
![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/20312621/03e2b2e4-a445-45d5-9243-41589dac2376)
![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/20312621/66b68c93-591c-4707-9ec3-e85965afd9e4)

**Comment by WGzeyu** [comment]
突然发现还有个问题，如果是报的危险网站则可以跳转，但跳转后会在结尾多加个/，导致部分网站触发404
![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/20312621/7b67ebec-e3e5-4140-9ff2-b6f255004eec)
![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/20312621/18769350-c2b8-4ab9-9ab1-d13be09a381d)
![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/20312621/9a15ee8b-b59a-448d-af27-b35d3c382d91)
![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/20312621/9cd6b8ef-7048-4221-8c10-c5f8a89b5100)

**Comment by WGzeyu** [comment]
（链接是通过QQNT Windows客户端点开的）

**Comment by WGzeyu** [comment]
突然发现危险网站这个可能是QQNT的bug...
![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/20312621/f69b52bd-0d64-43d3-98d4-fe9c028b2cc8)

![image](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/20312621/22d634a5-e46b-4d17-a522-819d968007ef)

**Comment by shi9uma** [comment]
1. 旧版 QQ windows 客户端（QQ 9.7.16，非 NT）点击链接被 **已停止访问该网页**，`https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now` -> `https://c.pc.qq.com/pc.html?url=https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now`；
    ![Snipaste_2024-01-15_23-22-32](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/75534705/02ffec22-6af0-439b-8ab7-0ee36d9390fe)
2. QQ NT 安卓版（V 9.0.0）点击链接被 **已停止访问该网页**，`https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now` -> `https://c.pc.qq.com/android.html?url=https://greasyfork.org/zh-CN/scripts/412612-open-the-f-king-url-right-now`；
    ![QQ图片20240115232828](https://github.com/OldPanda/Open-the-F-king-URL-Right-Now/assets/75534705/81347fcf-d86e-4282-a7a4-2dbfddb895d3)

**Comment by OldPanda** [comment]
我在 mac 客户端上也复现了这个问题
